name: ext-swoole

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: configure
      run: phpize && ./configure --enable-sockets --enable-mysqlnd --enable-http2 --enable-debug-log
    - name: make
      run: make
